# Generated by Django 3.1.4 on 2021-04-08 17:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhoenixApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='eventtype',
        ),
        migrations.AddField(
            model_name='previousevent',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='result',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='eventname'),
        ),
        migrations.AlterField(
            model_name='result',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='eventname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PhoenixApp.previousevent'),
        ),
        migrations.AlterField(
            model_name='result',
            name='studentname',
            field=models.CharField(default='', max_length=60),
        ),
    ]
