# Generated by Django 3.1.4 on 2021-05-20 14:12

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PhoenixApp', '0002_auto_20210408_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=250)),
                ('department', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('image', models.FileField(upload_to='Creativarty/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previousevent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
