# Generated by Django 3.1.4 on 2021-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoenixApp', '0003_auto_20210520_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizomania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
